In [1]:
import pandas as pd
import numpy as np

In [2]:
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)

False

np.nan in a special null value for numpy

In [4]:
a = np.array([1, 2, np.nan, 3, 4])

In [5]:
np.isnan(a)

array([False, False,  True, False, False])

In [6]:
a.sum()
a.mean()

nan

np.inf in for infinite type

In [7]:
3 + np.inf

inf

In [8]:
b = np.array([1, 2, 3, np.nan, np.inf, 6, 7])

In [9]:
b.dtype

dtype('float64')

In [10]:
b.sum()

nan

In [11]:
b.mean()

nan

In [12]:
np.isinf(b)

array([False, False, False, False,  True, False, False])

Lets filter out only valid values (i.e not Nan and not infinite)

In [13]:
valid_array = b[(~np.isnan(b)) & (~np.isinf(b))]

In [14]:
valid_array

array([1., 2., 3., 6., 7.])

In [17]:
valid_array.sum()

19.0

In [18]:
valid_array.std()

2.3151673805580453

In [19]:
valid_array.mean()

3.8