### Basics of numpy

In [1]:
import numpy as np

In [67]:
a = np.array([1, 2, 3, 4])

In [68]:
print(a[0], a[1])

1 2


In [69]:
b = a[0:]

In [70]:
b[[0, 2, -1]]

array([1, 3, 4])

In [71]:
c = b[[0, 2, -1]]
c

array([1, 3, 4])

In [72]:
c[0]

1

In [73]:
age = np.array([12, 18, 19, 21], dtype=np.int8)

In [74]:
age

array([12, 18, 19, 21], dtype=int8)

In [75]:
age.dtype

dtype('int8')

### Dimensions and shapes

In [76]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [77]:
A.size

6

In [78]:
A.shape

(2, 3)

In [79]:
A.ndim

2

In [80]:
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [0, 1, 2]
    ]
])

In [81]:
B.size

12

In [82]:
B.shape

(2, 2, 3)

In [83]:
B.ndim

3

### Indexing and slicing matrices

In [84]:
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [0, 1, 2]
    ]
])

In [85]:
B[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
B[0][0]

array([1, 2, 3])

In [87]:
B[0:]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [88]:
B[0][0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
B[1][0, 0]

7

In [90]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [91]:
A.ndim

2

In [92]:
A.shape

(3, 3)

In [93]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [94]:
A[1] = np.array([10, 12, 13])

In [95]:
A

array([[ 1,  2,  3],
       [10, 12, 13],
       [ 7,  8,  9]])

### Summary statistics

In [96]:
a = np.array([1, 2, 3, 4, 5])

In [97]:
a.sum()

15

In [98]:
a.mean()

3.0

In [99]:
a.max()

5

In [100]:
a.var()

2.0

In [101]:
a.std()

1.4142135623730951

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [4]:
# This sums the elements of every column and returns an array
A.sum(axis=0) 

array([12, 15, 18])

In [104]:
# This sums the elements of every row and returns an array
A.sum(axis=1)

array([ 6, 15, 24])

### Broadcasting and Vectorized operations

In [105]:
a = np.arange(4)

In [106]:
a

array([0, 1, 2, 3])

In [107]:
a + 10

array([10, 11, 12, 13])

In [108]:
a * 10

array([ 0, 10, 20, 30])

In [109]:
a += 100

In [110]:
a

array([100, 101, 102, 103])

In [111]:
a -= 100

In [112]:
a

array([0, 1, 2, 3])

In [113]:
a *= 100

In [114]:
a

array([  0, 100, 200, 300])

In [115]:
b = np.arange(4)

In [116]:
b

array([0, 1, 2, 3])

In [117]:
a = np.arange(4)

In [118]:
a

array([0, 1, 2, 3])

In [119]:
a + b

array([0, 2, 4, 6])

In [120]:
b = np.array([10, 10, 10 , 10])

In [121]:
a + b

array([10, 11, 12, 13])

In [122]:
a = a + b

In [123]:
a

array([10, 11, 12, 13])

### Boolean arrays

_Boolean operators returns boolean array which are used to filter out the array (list in python).

In [124]:
a = np.arange(4)

In [125]:
a

array([0, 1, 2, 3])

In [126]:
a[[True, False, True, False]]

array([0, 2])

In [127]:
a[[0, 2]]

array([0, 2])

In [128]:
a >= 2

array([False, False,  True,  True])

In [129]:
a[a>=2]

array([2, 3])

In [130]:
a.mean()

1.5

In [132]:
a[~(a > a.mean())]

array([0, 1])

In [133]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [134]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [135]:
A = np.random.randint(100, size=(3,3))

In [137]:
A

array([[15, 83, 16],
       [23,  3, 10],
       [72, 54, 68]])

In [138]:
A[A>30]

array([83, 72, 54, 68])